spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/bankdb  # Port 5435 for Docker PostgreSQL
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.shotaroi.bank: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
  expiration-ms: 86400000
